### ISSUE TITLE
Utilize html5 for javascript selections

### ISSUE THREAD

**Issue by vwbusguy** [vwbusguy/band-schedule#16]
Some tasks, particularly events, use some tricky gymnastics to gather the necessary data to perform tasks, such as parsing out a parent id or class tag.  This is reliable but not elegant and means at least some measure of code duplication between the events page and event detail pages.

Therefore, I'm considering utilizing html5 datasets to accomplish this instead: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_data_attributes

The downsides are that it will take time to test and recode, and that it will essentially break the app for IE10 and older (bonus?).  The upsides are cleaner code and it will make the transition to a native app in Cordova much nicer.

**Comment by vwbusguy** [comment]
Marking this as a "question" since my intent is to get feedback if there are any opinions on this.  I'll close it out within a week if there's no input.

**Comment by ParadoxGuitarist** [comment]
I'm in favor of moving to html5

**Comment by vwbusguy** [comment]
To be clear, this is anyway html5. We'd just be moving to using an html5
explicit feature for some javascript references.  There's no change in
doctype, but not all browsers support data attributes.
