### ISSUE TITLE
General Nomenclature

### ISSUE THREAD

**Issue by vwbusguy** [vwbusguy/band-schedule#21]
I'd like to get feedback on the nomenclature throughout the site.  For instance, band members don't generally refer to themselves as "users" unless it's in a very different context!  While "users" makes sense from a backend perspective, the wording could be more intuitive.

Possible examples:

"Event Users" => "Event Crew"
"Confirmed Users" => "Confirmed Members"

**Comment by ParadoxGuitarist** [comment]
Crew would be applicable to support roles (Sound, Media, ect.) but misleading for Musicians. 

Members could also be confused with Church membership. 

Might be best for a more generic term: People, person(s), muso(s), Worshiper(s),  teammate.... Personally I think people might be best.
